name: CI

on: [push, pull_request]

jobs:

  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        otp: [24, 26, 27]
    runs-on: ubuntu-22.04
    container:
      image: erlang:${{ matrix.otp }}

    steps:

    - uses: actions/checkout@v2

    - name: Cache rebar3
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/rebar3/
        key: ${{matrix.otp}}-${{hashFiles('rebar.config')}}

    - run: rebar3 compile
    - run: rebar3 xref
    - run: rebar3 dialyzer
