name: hexpm-release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-24.04
    container:
      image: erlang:26
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Publish to hex.pm
        run: DIAGNOSTIC=1 rebar3 hex publish --repo hexpm --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
